# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Building Maven'

- task: Maven@3
  inputs:

    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sqMavenPluginVersionChoice: 'latest'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'hello-world.war'
    replaceExistingArchive: true  
- task: CopyFiles@2
  inputs:
    sourceFolder: ./dist
    targetFolder: $(Build.ArtifactStagingDirectory)    
- task: PublishBuildArtifacts@1
 